export const RESET_APP_MODAL = 'RESET_APP_MODAL'
export const SETTINGS_MODAL = 'SETTINGS_MODAL'
export const DELETE_EXCHANGE_API = 'DELETE_EXCHANGE_API'

export default {
  RESET_APP_MODAL,
  SETTINGS_MODAL,
  DELETE_EXCHANGE_API
}
